spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/testit
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
